### ISSUE TITLE
Cuando eliminas al se busca no te deja cogerlo

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#12]
Description

En el nivel Pinepeak cuando luchas contra el boss y lo eliminas no te deja cogerlo ni matarlo además el pajaro que acompaña siempre al jugador no parece llevar el objeto de la suerte.

Reproduction Steps
Step1-> Juega hasta el nivel de Pinepeak.
Step2-> Lucha contra el bos de ese nivel y eliminalo.
Step2-> Comprueba como después de eliminarlo no te deja coger al se busca ni matarlo, pues no te da ninguna opción, además sigue disparando, cosa que no tendría que pasar.

Build 1.0.0.1

The first build in which this bug was found

Happens on Steam version? (yes/no)

Screenshot

![Captura](https://user-images.githubusercontent.com/58690864/79328521-778da100-7f16-11ea-9566-019834267fbb.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4480702/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4480704/TASaveGame.txt)

**Comment by alejandro-2awesome** [comment]
Esto no es un boss...

**Comment by david-santiago-21aswesome** [comment]
SOLVED
