### ISSUE TITLE
Falla el carro de la mina

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#15]
Description

Cuando te subes al carro de la mina y este se empieza a deslizar si te subes en el no te quedas encima, sino que te caes, dicho de otro modo, te subes y el jugador no se mueve con el carro, sino que se queda atrás.

Reproduction Steps
Step1->Juega en el nivel de Goldberg.
Step2-> Ves hasta el carrito de la mina y sube te en el. 
Step3-> Comprueba que el jugador se queda subido en el carro minero y no se cae.

Build 1.0.0.2

The first build in which this bug was found

Happens on Steam version? (yes/no)

Screenshot

![Captura](https://user-images.githubusercontent.com/58690864/79851135-32a9b480-83c5-11ea-87d3-7b2a52c9afb1.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4509082/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4509085/TASaveGame.txt)

**Comment by alejandro-2awesome** [comment]
Tienes que empujarlo, no? Si lo empujas va bien @david-santiago-21aswesome

**Comment by david-santiago-21aswesome** [comment]
Si tienes que empujarlo, pero yo me refiero a que si te subes en el no te lleva sino que el carro de la mina se va y tu te quedas atrás!!!
