### ISSUE TITLE
Cuando luchas contra el Boss el jugador se puede salir de pantalla

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#18]
Description

Cuando luchas contra el Boss el jugador se puede salir de pantalla, tanto por la derecha como por la izquierda.

Reproduction Steps
Step1->Juega en el nivel de Goldberg.
Step2-> Pasate el nivel y lucha contra el boss.
Step3-> Comprueba como el jugador se puede salir de la pantalla.

Build 1.0.0.2

The first build in which this bug was found

Happens on Steam version? (yes/no)

Screenshot

![Captura](https://user-images.githubusercontent.com/58690864/79854056-26275b00-83c9-11ea-89bd-56cc21fdd75d.PNG)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4509234/TASaveGame.txt)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4509235/output_log.txt)

**Comment by alejandro-2awesome** [comment]
No es un bug, ya estaba asi
