### ISSUE TITLE
Wrong text on recordings when "New Game"

### ISSUE THREAD

**Issue by alejandro-2awesome** [2awesomestudio/Luckslinger_IssueTracker#2]
**Description**
When trying to start a new game, on the empty recordings it shows "Recording Corrupt" instead 
of "New Recording" after visiting the continue option

**Reproduction Steps**
Open the game until the main menu
Click on Continue
Go Back to the main menu
Try to start a new game and observe the wrong caption

**Build**
1.0.0.0

**Happens on Steam version?** yes

**Screenshot**

![image](https://user-images.githubusercontent.com/8968755/78907488-0f0b7380-7a81-11ea-92d7-1aefe8fd3ba2.png)

**Comment by gregori2awesome** [comment]
Fixed

**Comment by david-santiago-21aswesome** [comment]
Solved
