### ISSUE TITLE
Hay una caja que pasas por al lado y normalmente las tienes que sortear 

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#21]
Description

Cuando juegas en morton expres en uno de los  vagones después del primer save aparece una caja que no la tienes que sortear, es decir que no hace falta que la saltes, es como si no estuviera ahí, ocurre en dos ocasiones. 

Reproduction Steps
Step1->Juega en el nivel de Morton Express.
Step2-> juega hasta que en uno de los vagones después del primer save aparece una caja que no la tienes que saltar.

Build 1.0.0.2

The first build in which this bug was found

Happens on Steam version? (yes/no)

Screenshot

![Captura](https://user-images.githubusercontent.com/58690864/79856572-ccc12b00-83cc-11ea-8b8e-86a1eb31ae00.PNG)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4509380/TASaveGame.txt)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4509381/output_log.txt)

Screenshot->1

![Captura](https://user-images.githubusercontent.com/58690864/79857640-6210ef00-83ce-11ea-8605-38a6b222f1fd.PNG)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4509442/TASaveGame.txt)

**Comment by alejandro-2awesome** [comment]
Si, me lo he mirado a fondo y es asi. Esas cajas son las que salen enemigos de ellas. 
Cuando lo leas, cierra este bug @david-santiago-21aswesome
