### ISSUE TITLE
Un enemigo se queda picando en vez de lanzarme el hacha

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#23]
Description

Un enemigo se queda picando en vez de lanzarme el hacha, en el nivel de Goldberg.
( Solo ocurre una vez )

Reproduction Steps
Step1-> Juega en el nivel de Goldberg.
Step2->Lucha contra enemigos para comprobar que actúan correctamente.

Build 1.0.0.3

The first build in which this bug was found

Happens on Steam version? (yes/no)

Screenshot

![Captura](https://user-images.githubusercontent.com/58690864/79965412-43712d80-848c-11ea-9e4b-2d4a7c7b3a60.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4515146/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4515148/TASaveGame.txt)

**Comment by alejandro-2awesome** [comment]
Si no los puedes reproducir no los abras, apuntatelos en tu libreta o en otro sitio, pero no los abras. A mi no me pasa.

**Comment by david-santiago-21aswesome** [comment]
ya no pasa, closed

**Comment by david-santiago-21aswesome** [comment]
Solved
