### ISSUE TITLE
Cuando eliminas al boss los otros enemigos no cesan de disparar

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#24]
Description

Cuando juegas en morton expres cuando eliminas al boss los otros enemigos no cesan de disparar
Reproduction Steps
Step1->Juega en el nivel de Morton Express.
Step2-> Juega hasta el boss.
Step3-> Elimina al boss
Step4-> Comprueba como los enemigos que quedan en pie siguen disparando al jugador.

Build 1.0.0.3

The first build in which this bug was found

Happens on Steam version

Screenshot

![Captura](https://user-images.githubusercontent.com/58690864/79976594-2d1f9d80-849d-11ea-803a-9f7cb7c179d4.PNG)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4515677/TASaveGame.txt)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4515778/output_log.txt)

**Comment by david-santiago-21aswesome** [comment]
Sigue pasando!!

**Comment by gregori2awesome** [comment]
Solved. Should be under testing

**Comment by david-santiago-21aswesome** [comment]
Lo he probado y no lo he podido probar ya que los enemigos que caían del techo del vagón ya no caen, así pues ahora ya no queda queda nadie quien dispare después de que mate al boss, entonces mi pregunta Gregori lo doy por bueno y cierro el bug?

**Comment by gregori2awesome** [comment]
@david-santiago-21aswesome No, son estados del boss, tiene que estar lanzando enemigos, pruebalo hasta que suelte los enemigos.

**Comment by david-santiago-21aswesome** [comment]
Solved
