### ISSUE TITLE
Las serpientes no aparecen

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#25]
**Description**
En el nivel de Blondies, cuando estás en dos de las salas que están vacías te lanzan corazones y serpientes, pues bien faltan las serpientes. ( Solo ha pasado una vez )

**Reproduction Steps**
Step1->Juega en el nivel de Blondies.
Step2->Comprueba como en las salas vacías donde te lanzan por las ventanas corazones, no te lanzan como debería ser las serpientes

**Build**1.0.0.3

**Happens on Steam version? (yes/no)**

**Screenshot**

![Captura](https://user-images.githubusercontent.com/58690864/80073383-fc487280-8547-11ea-967f-69a1ff29ee60.PNG)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4521007/TASaveGame.txt)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4521057/output_log.txt)

**Comment by gregori2awesome** [comment]
Checked. This are a lucky birds, meaning that can throw snakes or hears:

![imagen](https://user-images.githubusercontent.com/60605418/94041741-ef67cd80-fdca-11ea-85a5-b13d957d487b.png)

**Comment by david-santiago-21aswesome** [comment]
La etiqueta inválido que significa?

**Comment by gregori2awesome** [comment]
No es ningún bug, los pájaros te pueden tirar corazones o serpientes, es aleatorio dependiendo de la suerte que tengas
