### ISSUE TITLE
En el salón no puedes acceder a la parte superior del salón

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#27]
**Description**

Después del nivel sweetwater, cuando entregas al se busca, si vas al salón verás que no puedes subir a la parte de arriba, pues las plataformas que había han desaparecido.

**Reproduction Steps**
Step1->Después del nivel Sweetwater ves a Cloyercreek por quinta vez.
Step2->Entregas al se busca, comprueba como en el salón no puedes subir a la parte de arriba, pues las plataformas que había han desaparecido. 

**Build** 1.0.0.3

**Happens on Steam version? (yes/no)**

**Screenshot**

![Captura](https://user-images.githubusercontent.com/58690864/80085164-273ac280-8558-11ea-94e8-2d326dcf8604.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4521631/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4521633/TASaveGame.txt)

**Comment by alejandro-2awesome** [comment]
Si no mueves el jugador a la derecha la camara no se mueve. Pruebalo y me dices

**Comment by david-santiago-21aswesome** [comment]
solicionado,closed
