### ISSUE TITLE
El enemigo antes del boss el de la ataud no dispara bien su metralleta 

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#29]
**Description**

El enemigo antes del boss el de la ataud no dispara bien su metralleta en el nivel de Pinepeak, es decir que si dispara y si te acercas a el te daña pero si te alejas las balas no te alcanzan.

**Reproduction Steps**
Step1->Juega el nivel de Pinepeak.
Step2->Comprueba como el enemigo antes del boss el de la ataud no dispara bien su metralleta, si te acercas a el te daña pero si te alejas las balas no te alcanzan.

**Build** 1.0.0.3

**Happens on Steam version? (yes/no)**

**Screenshot**

![Captura](https://user-images.githubusercontent.com/58690864/80089091-b8f8fe80-855d-11ea-9b51-4bd15290a1ab.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4521806/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4521807/TASaveGame.txt)

**Comment by david-santiago-21aswesome** [comment]
sigue pasando

**Comment by gregori2awesome** [comment]
Fixed. Must be tested

**Comment by david-santiago-21aswesome** [comment]
Solved
