### ISSUE TITLE
Input stops working

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#3]
**Description**
Once you reach Clovercreek and you enter the saloon for the first time, the input stops working correctly. 

**Reproduction Steps**
Step1-> Start the game with no previous savegame
Step2-> Start a new game
Step3-> Once you reach Clovercreek enter the saloon
Step4-> The controls will not work anymore. 

**Build 1.0.0.0**

**Happens on Steam version? (yes/no)**
NO

**Screenshot**
![los_botones_no_funcionan](https://user-images.githubusercontent.com/58690864/78927454-3b35ed00-7a9f-11ea-9c8b-f68d463b2cc4.png)

**Comment by alejandro-2awesome** [comment]
[output_log (1).txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4464519/output_log.1.txt)

**Comment by alejandro-2awesome** [comment]
Problem with script execution order and when catching the rigidbody on the PlayerJumpComponent of the player

**Comment by david-santiago-21aswesome** [comment]
SOLVED
