### ISSUE TITLE
Los boss de Pinepeak no funcionan correctamente

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#30]
**Description**

Los boss  en el nivel de Pinepeak no disparan bien algo parecido al problema del enemigo de la ataud, sus disparos se ven pero no pasan más allá de un centímetro de su lado, es decir que si dispara y si te acercas a el te daña pero si te alejas las balas no te alcanzan, y cuando cruzan sombreros ese ataque si te daña.

**Reproduction Steps**
Step1->Juega el nivel de Pinepeak.
Step2->Comprueba como los boss no dispara bien sus pistolas, si te acercas a el te daña pero si te alejas las balas no te alcanzan, pero cuando cruzan sombreros ese ataque si te daña.

**Build** 1.0.0.3

**Happens on Steam version? (yes/no)**

**Screenshot**
![Captura](https://user-images.githubusercontent.com/58690864/80090091-41c46a00-855f-11ea-91dd-f323dd8c3044.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4521867/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4521872/TASaveGame.txt)

**Comment by gregori2awesome** [comment]
Fixed. Must be tested

**Comment by david-santiago-21aswesome** [comment]
Solved
