### ISSUE TITLE
El hermano de uno de los se busca no funciona correctamente

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#31]
**Description**

Después  del nivel de Pinepeak y de que dejas al boss en Creyencreek6 aparece el hermano de uno de los se busca que ya capturaste, pero este no funciona bien por varios motivos, uno es que no anda sino que se desliza como si fuera en patines, y lo segundo es que no puedes disparar solo lanzar el cuchillo y el tampoco dispara, y al principio se movía pero luego se quedo quieto inmobil. 

**Reproduction Steps**
Step1->Juega el nivel de Pinepeak y vuelve a Cloyercreek.
Step2->Deja al boss en la celda.
Step3->Comprueba como el hermano de uno de los se busca que ya capturaste, pero este no funciona bien por varios motivos, uno es que no anda sino que se desliza como si fuera en patines, y lo segundo es que no puedes disparar solo lanzar el cuchillo y el tampoco dispara, y al principio se movía pero luego se quedo quieto inmobil. 

**Build** v1.0.0.3-v10.0.5

**Happens on Steam version? (yes/no)**

**Screenshot**

![Captura](https://user-images.githubusercontent.com/58690864/80092759-a386d300-8563-11ea-9236-f0952d9d7f86.PNG)

![Captura](https://user-images.githubusercontent.com/58690864/94540847-3c262b00-0247-11eb-8886-347323685cb3.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5298399/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5298397/TASaveGame.txt)

**Comment by david-santiago-21aswesome** [comment]
Sigue pasando lo mismo en la Build v10.0.5

**Comment by gregori2awesome** [comment]
Fixed :P

**Comment by david-santiago-21aswesome** [comment]
Solved
