### ISSUE TITLE
No te deja subir al caballo

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#32]
**Description**

Cuando has luchado contra el último boss en cloyercreek6 toda la gente se va al final del pueblo para despedirte y hay un caballo que se supone que es para que te montes y te vallas para así finalizar el juego, pero no te deja subir al caballo.

**Reproduction Steps**
Step1->Juega el nivel de Pinepeak y vuelve a Cloyercreek.
Step2->Deja al boss en la celda.
Step3->Comprueba como después de haber eliminado al hermano que  de uno de los se busca que ya capturaste y es el último boss, después no te deja subir al caballo al final del pueblo, para finalizar la partida.

**Build** 1.0.0.3

**Happens on Steam version? (yes/no)**

**Screenshot**

![Captura](https://user-images.githubusercontent.com/58690864/80094404-7b4ca380-8566-11ea-8c78-6c7d5eb87ca0.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4522158/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4522159/TASaveGame.txt)

**Comment by gregori2awesome** [comment]
@david-santiago-21aswesome Porque comentas que no te deja subir al caballo? El juego original se subía al caballo y se iba? Porque al salir de la pantalla Luckslinger cogé el cofre de los lingotes de oro y se va:

![imagen](https://user-images.githubusercontent.com/60605418/94442165-eea4b200-01a3-11eb-902b-917b75cb7ec9.png)

**Comment by david-santiago-21aswesome** [comment]
Vale yo creía que se tenía que subir al caballo, pero bueno si siempre ha sido así pues resuelto

**Comment by david-santiago-21aswesome** [comment]
Solved
