### ISSUE TITLE
Become invencible at level 5

### ISSUE THREAD

**Issue by alejandro-2awesome** [2awesomestudio/Luckslinger_IssueTracker#33]
**Description:**
I seem to turn invincible after getting hit once. So I can take 1 damage, and then I become invincible after that 1 damage.

**Reproduction Steps:**
Go into level 5. Get hit once. Get hit again and see if you take damage or are also invincible. 

**Build:**
1.0.0.1

Happens on Steam version? (yes/no)
[output_log_-_when_turned_invincible_in_level_5.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4532751/output_log_-_when_turned_invincible_in_level_5.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4532752/TASaveGame.txt)

**Comment by gregori2awesome** [comment]
I need more info about that bug, which is the lvl 5?

**Comment by gregori2awesome** [comment]
Fixed. Must be tested.

**Comment by david-santiago-21aswesome** [comment]
Solved
