### ISSUE TITLE
Texto se sale del recuadro

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#34]
**Descripción**

Cuando vas a empezar una partida y estas en partidas guardas en idioma Español, debajo de "Nueva grabación" pone la frase -Comenzar a bendecir el micrófono- pues esa frase se sale del recuadro.
Pasos de reproducción

**Paso 1**-> Empieza una partida nueva. 
**Paso 2**-> Comprueba como en el menú de partidas guardadas el texto de -Comenzar a bendecir el micrófono- se sale del recuadro-

**Construir** 1.0.0.7

**Ocurre en la versión de Steam? (sí No)**

**Captura de pantalla**

![LS](https://user-images.githubusercontent.com/58690864/82795175-e9d99580-9e73-11ea-8615-0866851f37de.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5316463/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5316466/TASaveGame.txt)

**Comment by gregori2awesome** [comment]
Fixed

**Comment by david-santiago-21aswesome** [comment]
Sigue pasando en la build 10.0.7

**Comment by gregori2awesome** [comment]
Fixed
![imagen](https://user-images.githubusercontent.com/60605418/94927371-70595000-04c2-11eb-9f7c-d5043f4a3599.png)

**Comment by david-santiago-21aswesome** [comment]
Solved
