### ISSUE TITLE
Sheriff defectuoso después de Morton Express

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#38]
**Descripción**

Después del Morton Express cuando hablas con el sheriff para que te dibuje el cartel de se busca el está en la terraza del salón y cuando terminas de hablar con el se cae, bien si tu sales del salón como es debido, es decir por la puerta, el sheriff vuelve a aparecer arriba en la terraza,, lo que tienes que hacer es tirarte tu también por la terraza.
**Pasos de reproducción**
**Paso 1** juega el nivel de Morton Express y vuelve a Cloyercreek.
**Paso 2** Habla con el sheriff y comprueba como cuando hablas con el y se cae al suelo y tu sales por la puerta del salón el vuelve a estar en la terraza.

**Construir** 1.0.0.3

**Ocurre en la versión de Steam? (sí No)**

**Captura de pantalla**

![sheriff](https://user-images.githubusercontent.com/58690864/82804160-185e6d00-9e82-11ea-8a6a-5225b98f2ecd.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4676716/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4676721/TASaveGame.txt)

**Comment by gregori2awesome** [comment]
Solved. Must be tested

**Comment by david-santiago-21aswesome** [comment]
Solved
