### ISSUE TITLE
Los enemigos que disparan balas no funcionan bien

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#39]
**Description**

En el nivel de Pinepeak los enemigos que disparan balas no disparan a más de un os centimetros de distancia, si te acercas si te dañan pero si te alejas no(solo pasa con los que disparan lento, pues con los que disparan rápido parece ir bien).

**Reproduction Steps**

**Step1** Juega en el nivel de pinepeak.
**Step2** Comprueba como los enemigos que disparan balas no disparan más lejos de unpar de cetímetros.

**Build** 1.0.0.3

**Happens on Steam version? (yes/no)**

**Screenshot**

![Captura](https://user-images.githubusercontent.com/58690864/82808979-5f9d2b80-9e8b-11ea-9dc2-ccac7850bc05.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4676957/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4676961/TASaveGame.txt)

**Comment by gregori2awesome** [comment]
Fixed. Must be tested

**Comment by david-santiago-21aswesome** [comment]
Solved
