### ISSUE TITLE
El primer deposito de agua que encuentras no cae

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#4]
Description
El primer deposito de agua que encuentras no cae, es decir cuando pasas por debajo no cae encima del jugador, solo me ha pasado una vez.

Reproduction Steps
Step1->Juega dese el principio y llega hasta el primer deposito de agua.
Step2->Comprueba que no se cae encima del jugador.

Build 1.0.0.0

The first build in which this bug was found

Happens on Steam version? (yes/no)
NO
Screenshot

**Comment by 2awesomestudio** [comment]
Es correcto
