### ISSUE TITLE
El jinete no dispara bien

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#40]
**Description**

En el nivel de Pinepeak el jinete no disparan bien hace el ruido pero no disparai.

**Reproduction Steps**
**Step1** Juega en el nivel de Pinepeak.
**Step2** Juega hasta llegar hasta el jinete y comprueba que no dispara bien.

**Build** 1.0.0.3

**Happens on Steam version? (yes/no)**

**Screenshot**

![Captura](https://user-images.githubusercontent.com/58690864/82809723-0fbf6400-9e8d-11ea-95e8-db5029cdb191.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4677005/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4677007/TASaveGame.txt)

**Comment by gregori2awesome** [comment]
Tested and works fine - shoot sound is working when a bullet is displayed - also the bullets do damage to the player

**Comment by david-santiago-21aswesome** [comment]
Solved
