### ISSUE TITLE
El enemigo de la ataúd antes del Boss se queda bloqueado 

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#42]
**Description**

El enemigo antes del boss el de la ataúd se queda bloqueado en el nivel de Pinepeak, es decir que al principio si funciona correctamente, pero después de digamos 3 vueltas más o menos se queda bloqueado sin hacer nada en un lado de la pantalla como se muestra en la imagen, entonces lo que hice fue ponerme detrás de él y dispararle por detrás para matarlo y así llegar al Boss y comprobar el último bug, pero dispare dos veces y me dejo de funcionar la pistola solo eso pues todo lo demás me funcionaba correctamente, asique lo mate con el cuchillo, una vez hecho eso seguí avanzando hacia el Boss y como se muestra en la imagen el jugador se quedo bloqueado y no funcionaba ninguna función del mando..

**Reproduction Steps**

**Step1->**J uega el nivel de Pinepeak.
**Step2->** Comprueba como el enemigo antes del boss el de la ataúd al luchar contra él al principio si funciona correctamente, pero después de digamos 3 vueltas más o menos se queda bloqueado sin hacer nada en un lado de la pantalla como se muestra en la imagen

**Step3->** Avanza por el nivel pinepeak una vez pasado el enemigo de la ataúd.
**Step4->** Comprueva como en un sitio dado donde se muestra en la imagen el jugador se queda bloqueado y no funciona ninguna acción del mando.

**Build** 1.0.0.4

**Happens on Steam version? (yes/no)**

**Screenshot**

![Captura](https://user-images.githubusercontent.com/58690864/94419403-03248280-0183-11eb-83cf-2be53459f346.PNG)

![Captura1](https://user-images.githubusercontent.com/58690864/94419422-0ae42700-0183-11eb-853f-ce6ae1a5e080.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5291473/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5291472/TASaveGame.txt)

**Comment by gregori2awesome** [comment]
Fixed

**Comment by david-santiago-21aswesome** [comment]
Solved
