### ISSUE TITLE
Los nombres nuestros no salen en los créditos solo  2Awesome Partners

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#43]
**Description**

Los nombres nuestros no salen en los créditos solo  2Awesome Partners
**Reproduction Steps**

**Step1** Pasa te el juego y llega hasta los créditos.
**Step2** Comprueba como no salen nuestros nombres en los créditos, pero si el de la empresa (2Awesome Partners)

**Build**
v10.0.5

The first build in which this bug was found

**Happens on Steam version? (yes/no)**

**Screenshot**

_*Attach the pic here if necessary or available

![Captura](https://user-images.githubusercontent.com/58690864/94549549-b01a0080-0252-11eb-83d1-159cfdfadf71.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5298388/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5298393/TASaveGame.txt)

**Comment by gregori2awesome** [comment]
![imagen](https://user-images.githubusercontent.com/60605418/95103053-6f2f5980-0734-11eb-89da-0df9b7c7c6d9.png)
