### ISSUE TITLE
Una vez seleccionado el idioma alemán hay un bug en el menú principal 

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#44]
**Description**

Una vez seleccionado el idioma alemán hay un bug en el menú principal, me explico no se si ya venía por defecto o no, ya que lo primero que hice fue cambiar el idioma al alemán, entonces probé los distintos idiomas y en el menú principal cuando le das a nueva partida; donde dice "Nueva escuela" o "Vieja escuela" eso está en alemán, independientemente del idioma que escojas 

**Reproduction Steps**

**Step1** Empieza la partida de Luckslinger.
**Step2** En el menú principal antes de comenzar a jugar, ves a ajustes y elige el idioma alemán.
**Step3** Luego selecciona cada uno de los idiomas que hay disponibles.
**Step4** Comprueba como en cada uno de los idiomas; inglés, español, francés, italiano, chino, coreano y japonés, en la opción de nueva escuela o vieja escuela sigue estando en alemán.

Etc.

**Build**
v10.0.6

The first build in which this bug was found
v10.0.6

**Happens on Steam version? (yes/no)**

**Screenshot**

_*Attach the pic here if necessary or available

**Esta imagen está tomada con el idioma italiano, pero pasa con todos**
![Ingles_frances_italiano_chino_coreano_japones](https://user-images.githubusercontent.com/58690864/94657772-40634e80-0302-11eb-84d2-d0377b7a0899.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5303856/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5303858/TASaveGame.txt)

**Comment by gregori2awesome** [comment]
Fixed

**Comment by david-santiago-21aswesome** [comment]
Solved
