### ISSUE TITLE
Cuando escoges el idioma Francés, Italiano y Chino en guardar partida después de nueva escuela el texto se sale del recuadro o tabla

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#45]
**Description**

Cuando escoges el idioma Francés, Italiano y Chino o japonés ya que no los identifico muy bien, pero te adjunto una imagen para que me digas si es uno u otro, en guardar partida donde los tres vinilos y después de elegir nueva escuela o vieja escuela el texto guardar partida  se sale del recuadro o tabla y, en inglés y chino sobreescribir también se sale de la tabla, pero además en el idioma alemán el texto que hay debajo de guardar nueva partida también se sale de la tabla.

**Reproduction Steps**

**Step1** Empieza la partida de Luckslinger.
**Step2** En el menú principal antes de comenzar a jugar, ves a ajustes y elige el idioma Francés, Italiano y Chino en un principio, sino japonés.
**Step3** Luego selecciona Nueva Partida y Nueva escuela.
**Step4** Comprueba como en  guardar partida donde los tres vinilos el texto  guardar nueva partida se sale del recuadro o tabla.
**Step5-NOTA:** El sobrescribir también se sale en el idioma inglés y chino, en los demás idiomas están bien.
**Step6-NOTA:** Pero además en el idioma alemán el texto que hay debajo de guardar nueva partida también se sale de la tabla.

**Build**
v10.0.6

The first build in which this bug was found
v10.0.6

**Happens on Steam version? (yes/no)**

**Screenshot**

_*Attach the pic here if necessary or available

**Esta es la del bug guardar Francés**
![frasnces](https://user-images.githubusercontent.com/58690864/94661391-43ad0900-0307-11eb-8de0-1050508ec24b.PNG)

**Y esta es la del bug guardar Italiano**
![italiano](https://user-images.githubusercontent.com/58690864/94661700-b28a6200-0307-11eb-889e-eaf232baafe6.PNG)

**Esta es para que veas que idioma es si chino o japonés**
![chino](https://user-images.githubusercontent.com/58690864/94659046-fc714900-0303-11eb-9fc4-a8afb4351f90.PNG)

**Y esta es la del bug guardar chino**
![chino1](https://user-images.githubusercontent.com/58690864/94659062-01ce9380-0304-11eb-8b6d-cf6375b7f236.PNG)

**Y esta es la del bug chino de sobreescribir**
![sobreescribir_chino](https://user-images.githubusercontent.com/58690864/94662525-cd110b00-0308-11eb-93cf-3b699d66161b.PNG)

**Y esta es la del bug inglés de sobreescribir y guardar nueva partida***
![sobrescribir_ingles](https://user-images.githubusercontent.com/58690864/94660016-71914e00-0305-11eb-96aa-2963ffb454c6.PNG)

**Y esta es la del bug en alemán del texto que hay debajo de guardar nueva partida también se sale de la tabla**
![guardado aleman](https://user-images.githubusercontent.com/58690864/94662947-63453100-0309-11eb-86df-30d813d1753c.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5303901/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5303902/TASaveGame.txt)

**Comment by gregori2awesome** [comment]
Fixed

**Comment by david-santiago-21aswesome** [comment]
Solved
