### ISSUE TITLE
En español debajo de sobreescribir partida el texto "Overture :$ 0" está en inglés

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#46]
**Description**

Cuando escoges el idioma español, en guardar partida donde los tres vinilos y después de elegir nueva escuela o vieja escuela el texto debajo de sobreescribir partida "Overture :$ 0" está en inglés.
Mi duda es si tiene que ser así o es un bug.

**Reproduction Steps**

**Step1** Empieza la partida de Luckslinger.
**Step2** En el menú principal antes de comenzar a jugar, ves a ajustes y elige el idioma español.
**Step3** Luego selecciona Nueva Partida y Nueva escuela.
**Step4** Comprueba como en  guardar partida donde los tres vinilos el texto el texto debajo de sobreescribir partida "Overture :$ 0" está en inglés.

**Build**
v10.0.6

The first build in which this bug was found
v10.0.6

**Happens on Steam version? (yes/no)**

**Screenshot**

_*Attach the pic here if necessary or available

![español_ vinilos](https://user-images.githubusercontent.com/58690864/94663640-2fb6d680-030a-11eb-8f97-2fb63a58dcd6.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5304166/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5304167/TASaveGame.txt)

**Comment by gregori2awesome** [comment]
@david-santiago-21aswesome Ese texto muestra el nombre del nivel o el del boss con el que vas a luchar.
