### ISSUE TITLE
El texto overture está en inglés en todos los idiomas

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#48]
**Description**

Cuando escoges cualquier idioma en guardar partida donde los tres vinilos y después de elegir nueva escuela o vieja escuela el texto  overture está en inglés en todos los idiomas.
**Reproduction Steps**

**Step1** Empieza la partida de Luckslinger.
**Step2** En el menú principal antes de comenzar a jugar, ves a ajustes y elige cualquier idioma menos inglés.
**Step3** Luego selecciona Nueva Partida y Nueva escuela.
**Step4** Comprueba como en  guardar partida donde los tres vinilos el texto   overture está en inglés en todos los idiomas.
**Step5-NOTA:** Esto pasa cuando ya tienes una partida guardada.

**Build**
v10.0.6-v10.0.7

The first build in which this bug was found
v10.0.6

**Happens on Steam version? (yes/no)**

**Screenshot**

_*Attach the pic here if necessary or available

![Captura](https://user-images.githubusercontent.com/58690864/94898666-3a03dc80-0492-11eb-8abd-a2e6751b30da.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5316516/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5316518/TASaveGame.txt)

**Comment by gregori2awesome** [comment]
Fixed 
![imagen](https://user-images.githubusercontent.com/60605418/94933688-06917400-04cb-11eb-9bc1-cafa339f0876.png)
