### ISSUE TITLE
El texto "His name was Sean" o "Save it for the cave" está en inglés en el idioma español

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#49]
**Descripción**

Cuando vas continuar una partida el texto "His name was Sean" o "Save it for the cave" debajo de "Reanudar" está en inglés en todos los idioma.

**Pasos de reproducción**

**Paso 1**-> Empieza una partida nueva. 
**Paso 2**-> Guarda la partida en un punto de control y salte de la partida.
**Paso 3**-> Dale clic a continuar y comprueba como  el texto "His name was Sean" o"Save it for the cave" debajo de "Reanudar" está en inglés en todos los idiomas.

**Construir** 1.0.0.7

**Ocurre en la versión de Steam? (sí No)**

**Captura de pantalla**

![Captura](https://user-images.githubusercontent.com/58690864/94913543-b950da80-04a9-11eb-842d-2eff415bdca4.PNG)

![Captura](https://user-images.githubusercontent.com/58690864/94916158-704f5500-04ae-11eb-806a-256d962eee25.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5317311/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5317312/TASaveGame.txt)

**Comment by gregori2awesome** [comment]
Fixed
