### ISSUE TITLE
Music options not working once changing scene

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#5]
**Description**
If you change the music volume in the options, it works on the current scene, but once you change scene, it goes to the default value. 

**Reproduction**
Step1->Go to the options menu in any scene
Step2->Change the music volume
Step3-> Continue playing until you change scene (playing a new level, entering a building, ...)
Observe how the music value rollback to its default value.  

**Build** 1.0.0.0

**Happens on Steam version? (yes/no)**
NO

**Screenshot**

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4462414/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4462435/TASaveGame.txt)

**Comment by alejandro-2awesome** [comment]
Sound Utils was still reading from PlayerPrefs instead of file

**Comment by david-santiago-21aswesome** [comment]
SOLVED
