### ISSUE TITLE
En el tejado de la entrada del Banco el jugador cuando salta lo atraviesa

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#51]
**Description**

En el tejado de la entrada del Banco el jugador cuando salta lo atraviesa como se ve en en la imagen.

**Reproduction Steps**

**Step1** Juega una partida nueva o ya empezada.

**Step2** ves hasta el banco y sitúate debajo del tejado de la entrada y salta. 

**Step3** comprueba como el jugador atraviesa dicho tejado.

**Build**
v10.0.8

**The first build in which this bug was found**
10.0.8

**Happens on Steam version? (yes/no)**

**Screenshot**
![tejado_banco](https://user-images.githubusercontent.com/58690864/95070982-42b21800-0709-11eb-886d-5ea11a4cbde9.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5326887/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/5326889/TASaveGame.txt)

**Comment by gregori2awesome** [comment]
Fixed in all levels
