### ISSUE TITLE
La conversación con el cura esta en ingles

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#7]
Description

La conversación con el cura esta en ingles

Reproduction Steps
Step1->juega en todos los niveles del cloyercreek y comprueba que las conversaciones con el cura dentro de la iglesia estan en ingles, cuando juegas en modo castellano

Build->1.0.0.0

The first build in which this bug was found

Happens on Steam version? (yes/no)

Screenshot

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4464950/output_log.txt)

**Comment by alejandro-2awesome** [comment]
Esta bien asi, son canciones.
