### ISSUE TITLE
Weird how player blocked by "air"

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#8]
**Description**
The player gets blocked in the wagon you can see in screenshot with something that "it is not there" 

**Reproduction Steps**
Step1-> Play the game until Morton Express level
Step2-> Check how when you arrive to the wagon as in the screenshot
Step3-> See how the player gets blocked

**Build 1.0.0.1**

**Happens on Steam version? (yes/no)**
YES

**Screenshot**
![Captura](https://user-images.githubusercontent.com/58690864/79215378-b276d280-7e4b-11ea-9f18-557f38ff7050.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4474734/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4474738/TASaveGame.txt)

**Comment by alejandro-2awesome** [comment]
Fixed, the collider was wrongly placed. Problem on Steam as well.

**Comment by david-santiago-21aswesome** [comment]
SOLVED
