### ISSUE TITLE
Music adjustments do not work in Blondies Casino

### ISSUE THREAD

**Issue by david-santiago-21aswesome** [2awesomestudio/Luckslinger_IssueTracker#9]
**Description**
The music volume settings do not work properly on Blondies Casino. 

**Reproduction Steps**
Step1-> At any moment disable the music (put music volume down)
Step2-> Play the game until Blondies casino
Step3-> See how the music volume is back to its original sound

**Build 1.0.0.1**

**Happens on Steam version**
NO

**Screenshot**

![Captura1](https://user-images.githubusercontent.com/58690864/79217860-d5a38100-7e4f-11ea-9885-643f09284f65.PNG)

[output_log.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4474869/output_log.txt)

[TASaveGame.txt](https://github.com/2awesomestudio/Luckslinger_IssueTracker/files/4474871/TASaveGame.txt)

**Comment by alejandro-2awesome** [comment]
Wrong usage of old PlayerPrefs instead of savegame

**Comment by david-santiago-21aswesome** [comment]
SOLVED
